language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- cd /tmp
- curl -L https://github.com/pololu/fastgpio-arduino/archive/master.tar.gz | tar xz

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=micro
- BOARD=yun

script:
- for e in examples/*; do
    platformio ci --board=$BOARD --lib="." --lib="/tmp/fastgpio-arduino-master/" $e/*;
  done
